<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('subcategories', function (Blueprint $table) {
            $table->id();
            $table->foreignId('categorie_id')->default(1)->constrained('categories');
            $table->string('code')->default('');
            $table->string('name');
            $table->foreignId('companie_id')->default(1)->constrained('companies');
            $table->foreignId('state_id')->default(1)->constrained('states');
            $table->timestamps();
            $table->timestamp('deleted_at')->nullable();

            $table->unsignedBigInteger('created_by')->nullable();
            $table->foreign('created_by')->references('id')->on('users');
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->foreign('updated_by')->references('id')->on('users');
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->foreign('deleted_by')->references('id')->on('users');
        });

        DB::table('subcategories')->insert(array('categorie_id'=>'1','name'=>'Sin Subcategoria'));
        DB::table('subcategories')->insert(array('categorie_id'=>'104','name'=>'<p>Medicamentos de Patente</p>'));
        DB::table('subcategories')->insert(array('categorie_id'=>'79','name'=>'1 a 3 años'));
        DB::table('subcategories')->insert(array('categorie_id'=>'79','name'=>'3 a 5 años'));
        DB::table('subcategories')->insert(array('categorie_id'=>'79','name'=>'5 años en adelante'));
        DB::table('subcategories')->insert(array('categorie_id'=>'97','name'=>'Accesorios'));
        DB::table('subcategories')->insert(array('categorie_id'=>'51','name'=>'Accesorios para Sushi'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Aceite para Muebles'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Aceites y Cremas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Aceitunas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'81','name'=>'Ácida'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Acondicionadores'));
        DB::table('subcategories')->insert(array('categorie_id'=>'85','name'=>'Aderezos y Jugos naturales'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Aderezos y Vinagretas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'40','name'=>'Agua Mineral'));
        DB::table('subcategories')->insert(array('categorie_id'=>'40','name'=>'Agua Natural'));
        DB::table('subcategories')->insert(array('categorie_id'=>'40','name'=>'Agua Quina'));
        DB::table('subcategories')->insert(array('categorie_id'=>'40','name'=>'Agua Saborizada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'31','name'=>'Agua y jugos para bebé'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Alcohol'));
        DB::table('subcategories')->insert(array('categorie_id'=>'109','name'=>'Alergias'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Algodón'));
        DB::table('subcategories')->insert(array('categorie_id'=>'64','name'=>'Alimento seco para Gatos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'64','name'=>'Alimento seco para perros'));
        DB::table('subcategories')->insert(array('categorie_id'=>'31','name'=>'Alimentos orgánicos para bebé'));
        DB::table('subcategories')->insert(array('categorie_id'=>'63','name'=>'Almidones'));
        DB::table('subcategories')->insert(array('categorie_id'=>'103','name'=>'Alta Especialidad'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Americano'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Añejo y cotija'));
        DB::table('subcategories')->insert(array('categorie_id'=>'90','name'=>'Anís y Jerez'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Anti acné'));
        DB::table('subcategories')->insert(array('categorie_id'=>'100','name'=>'Antiácidos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'97','name'=>'Anticonceptivos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'100','name'=>'Antidiarreicos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'50','name'=>'Antimicóticos Pies'));
        DB::table('subcategories')->insert(array('categorie_id'=>'50','name'=>'Antimicóticos Uñas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'100','name'=>'Antiparasitarios'));
        DB::table('subcategories')->insert(array('categorie_id'=>'65','name'=>'Aromatizante ambiental'));
        DB::table('subcategories')->insert(array('categorie_id'=>'66','name'=>'Arroz'));
        DB::table('subcategories')->insert(array('categorie_id'=>'39','name'=>'Arroz Instantáneo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'51','name'=>'Arroz y Pastas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'30','name'=>'Artesanal e Importada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Asadero y ranchero'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Ates y Chongos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'82','name'=>'Atole'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Atún y Pescados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'62','name'=>'Avena y Granola'));
        DB::table('subcategories')->insert(array('categorie_id'=>'78','name'=>'Azúcar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Bactericidas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'77','name'=>'Bagels'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Banditas y telas adhesivas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'62','name'=>'Barras de cereal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Base para maquillaje'));
        DB::table('subcategories')->insert(array('categorie_id'=>'67','name'=>'Bebidas de almendra'));
        DB::table('subcategories')->insert(array('categorie_id'=>'67','name'=>'Bebidas de arroz, avena y quinoa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'67','name'=>'Bebidas de coco'));
        DB::table('subcategories')->insert(array('categorie_id'=>'67','name'=>'Bebidas de soya'));
        DB::table('subcategories')->insert(array('categorie_id'=>'40','name'=>'Bebidas mineralizadas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'91','name'=>'Blanco'));
        DB::table('subcategories')->insert(array('categorie_id'=>'89','name'=>'Blanqueador en Gel'));
        DB::table('subcategories')->insert(array('categorie_id'=>'89','name'=>'Blanqueador Líquido'));
        DB::table('subcategories')->insert(array('categorie_id'=>'25','name'=>'Bloqueadores y Bronceadores'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Bollos y Hot Dog'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Bolsas para Basura'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Bolsas para Cocina'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Bombones'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Botanas frías'));
        DB::table('subcategories')->insert(array('categorie_id'=>'80','name'=>'Botanas y Comida Infantil'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'brandy'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Brillos y gloss'));
        DB::table('subcategories')->insert(array('categorie_id'=>'35','name'=>'Bucales'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Cabaña'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Cacahuates y Habas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Café en grano'));
        DB::table('subcategories')->insert(array('categorie_id'=>'83','name'=>'Café listo para beber'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Café Molido'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Café Soluble e Instantáneo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'37','name'=>'Cajeta'));
        DB::table('subcategories')->insert(array('categorie_id'=>'110','name'=>'Calcio / Embarazo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'50','name'=>'Callos, Ampollas y Juanetes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'101','name'=>'Calzones Anatómicos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Canasto y fresco'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Canelones'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Capilares'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Cápsulas de café'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Caramelos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'72','name'=>'Carne empacada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'96','name'=>'Carne para hamburguesas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Carnes Enlatadas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Carnes frías de temporada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Carnes frías gourmet'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Catsup y Mostaza'));
        DB::table('subcategories')->insert(array('categorie_id'=>'57','name'=>'Cepillo dental'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Cera para Pisos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'31','name'=>'Cereales y galletas para bebé'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Cerillos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'44','name'=>'Champagne y Espumoso'));
        DB::table('subcategories')->insert(array('categorie_id'=>'73','name'=>'Champú y jabón para bebé'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Chicharrones'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Chicles'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Chihuahua'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Chiles Enlatados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'52','name'=>'Chiles Secos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Chistorra y Longaniza'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Chocolates'));
        DB::table('subcategories')->insert(array('categorie_id'=>'61','name'=>'Chocolates para repostería'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Chorizo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Cintas Kinesiológicas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'30','name'=>'Clara'));
        DB::table('subcategories')->insert(array('categorie_id'=>'91','name'=>'Claras y Especializados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'35','name'=>'Cólicos Menstruales'));
        DB::table('subcategories')->insert(array('categorie_id'=>'63','name'=>'Colorantes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'80','name'=>'Comida Congelada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'39','name'=>'Comida Rápida'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'Coñac'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'Condensada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'97','name'=>'Condones'));
        DB::table('subcategories')->insert(array('categorie_id'=>'109','name'=>'Congestión Nasal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'52','name'=>'Consomés'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Corrector'));
        DB::table('subcategories')->insert(array('categorie_id'=>'25','name'=>'Crema corporal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'37','name'=>'Crema de Cacahuate y Avellana'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Crema facial'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Crema para café'));
        DB::table('subcategories')->insert(array('categorie_id'=>'24','name'=>'Crema para manos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Crema para peinar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Crema y doble crema'));
        DB::table('subcategories')->insert(array('categorie_id'=>'73','name'=>'Crema, gel y loción para bebé'));
        DB::table('subcategories')->insert(array('categorie_id'=>'99','name'=>'Cremas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'39','name'=>'Cremas Instantáneas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Crutones'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Cubiertos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Cuidado Bucal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'76','name'=>'Cuidado de la Mujer'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Cuidado de la Piel'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Cuidado de los Labios'));
        DB::table('subcategories')->insert(array('categorie_id'=>'76','name'=>'Cuidado del Hombre'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Cuidado para Zapatos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'61','name'=>'De Arroz'));
        DB::table('subcategories')->insert(array('categorie_id'=>'29','name'=>'De Coco'));
        DB::table('subcategories')->insert(array('categorie_id'=>'62','name'=>'De Fibra y Light'));
        DB::table('subcategories')->insert(array('categorie_id'=>'29','name'=>'De Maíz'));
        DB::table('subcategories')->insert(array('categorie_id'=>'29','name'=>'De Oliva'));
        DB::table('subcategories')->insert(array('categorie_id'=>'29','name'=>'De Semillas y Vegetal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'61','name'=>'De Trigo y Maíz'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Delineador de labios'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Delineador de ojos y cejas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Dermocosméticos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Desinfectantes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Desmaquillante'));
        DB::table('subcategories')->insert(array('categorie_id'=>'25','name'=>'Desodorante femenino'));
        DB::table('subcategories')->insert(array('categorie_id'=>'25','name'=>'Desodorante masculino'));
        DB::table('subcategories')->insert(array('categorie_id'=>'50','name'=>'Desodorantes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Destapacaños'));
        DB::table('subcategories')->insert(array('categorie_id'=>'55','name'=>'Detergente en polvo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'55','name'=>'Detergente Líquido'));
        DB::table('subcategories')->insert(array('categorie_id'=>'35','name'=>'Dolor'));
        DB::table('subcategories')->insert(array('categorie_id'=>'100','name'=>'Dolor y Malestar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'81','name'=>'Dulce'));
        DB::table('subcategories')->insert(array('categorie_id'=>'62','name'=>'Dulce de cereales'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Dulces Enchilados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Ecológicos, entrenadores y para nadar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'72','name'=>'Empacada de soja'));
        DB::table('subcategories')->insert(array('categorie_id'=>'72','name'=>'Empacado'));
        DB::table('subcategories')->insert(array('categorie_id'=>'72','name'=>'Empacados Antojitos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Empanizador'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'En Polvo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'45','name'=>'Energizante'));
        DB::table('subcategories')->insert(array('categorie_id'=>'86','name'=>'Enfriadores'));
        DB::table('subcategories')->insert(array('categorie_id'=>'57','name'=>'Enjuague bucal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'70','name'=>'Ensaladas y empacados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Esmaltes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Espaguetis'));
        DB::table('subcategories')->insert(array('categorie_id'=>'79','name'=>'Especializadas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'52','name'=>'Especias'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'Evaporada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Fetuccine'));
        DB::table('subcategories')->insert(array('categorie_id'=>'84','name'=>'Fibras y esponjas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'78','name'=>'Flanes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Fondue'));
        DB::table('subcategories')->insert(array('categorie_id'=>'25','name'=>'Fragancias'));
        DB::table('subcategories')->insert(array('categorie_id'=>'66','name'=>'Frijol'));
        DB::table('subcategories')->insert(array('categorie_id'=>'39','name'=>'Frijoles Instantáneos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'94','name'=>'Fruta Congelada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'95','name'=>'Fruta seca'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Frutas en Almíbar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Frutas Secas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Fusilli'));
        DB::table('subcategories')->insert(array('categorie_id'=>'28','name'=>'Galletas de Avena y Cereal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'28','name'=>'Galletas Dulces'));
        DB::table('subcategories')->insert(array('categorie_id'=>'28','name'=>'Galletas Saladas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'109','name'=>'Garganta Irritada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Gasas y Vendas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Gel Antibacteriano'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Gel, mousse y spray'));
        DB::table('subcategories')->insert(array('categorie_id'=>'34','name'=>'Gelatina'));
        DB::table('subcategories')->insert(array('categorie_id'=>'78','name'=>'Gelatina de Agua en Polvo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'Ginebra'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Gomitas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'107','name'=>'Gotas para ojos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Gouda y edam'));
        DB::table('subcategories')->insert(array('categorie_id'=>'78','name'=>'Grenetina'));
        DB::table('subcategories')->insert(array('categorie_id'=>'109','name'=>'Gripa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Guantes y Cubrebocas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'80','name'=>'Hamburguesas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'51','name'=>'Harinas y Algas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'74','name'=>'Helados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'35','name'=>'Hemorroides'));
        DB::table('subcategories')->insert(array('categorie_id'=>'45','name'=>'Hidratante'));
        DB::table('subcategories')->insert(array('categorie_id'=>'92','name'=>'Hielo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'57','name'=>'Higiene bucal para niños'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Higiene Femenina'));
        DB::table('subcategories')->insert(array('categorie_id'=>'57','name'=>'Hilo dental y artículos especializados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Hisopos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'74','name'=>'Hot Cakes y Waffles'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Inmersión'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Insecticidas y Trampas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'25','name'=>'Jabón de tocador'));
        DB::table('subcategories')->insert(array('categorie_id'=>'54','name'=>'Jabón en Barra'));
        DB::table('subcategories')->insert(array('categorie_id'=>'60','name'=>'Jabón Íntimo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'24','name'=>'Jabón líquido'));
        DB::table('subcategories')->insert(array('categorie_id'=>'54','name'=>'Jabón Líquido y en Escamas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'87','name'=>'Jabón para lavavajillas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'25','name'=>'Jabón y gel corporal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Jack'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Jamón'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Jamón serrano'));
        DB::table('subcategories')->insert(array('categorie_id'=>'82','name'=>'Jarabe para Agua'));
        DB::table('subcategories')->insert(array('categorie_id'=>'98','name'=>'Jeringas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Jeringas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Jocoque'));
        DB::table('subcategories')->insert(array('categorie_id'=>'27','name'=>'Jugo de Frutas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'27','name'=>'Jugo de Verduras'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Labiales'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Lasaña'));
        DB::table('subcategories')->insert(array('categorie_id'=>'64','name'=>'Latas y Pouch para Gatos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'64','name'=>'Latas y Pouch para Perros'));
        DB::table('subcategories')->insert(array('categorie_id'=>'87','name'=>'Lavatrastes en polvo y en pasta'));
        DB::table('subcategories')->insert(array('categorie_id'=>'87','name'=>'Lavatrastes líquido'));
        DB::table('subcategories')->insert(array('categorie_id'=>'100','name'=>'Laxante'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'Leche Deslactosada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'Leche Entera'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'Leche Especializada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'Leche Light'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'Leche Saborizada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'41','name'=>'Leche Semi y Descremada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'66','name'=>'Leguminosas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'Licor'));
        DB::table('subcategories')->insert(array('categorie_id'=>'33','name'=>'Light y Sin Azúcar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Limpiadores de Baño'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Limpiadores de Cocina'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Limpiadores Multiusos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Lo mejor para la limpieza de tu hogar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'97','name'=>'Lubricantes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Maduros'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Manchego'));
        DB::table('subcategories')->insert(array('categorie_id'=>'29','name'=>'Manteca Vegetal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'32','name'=>'Mantequillas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'32','name'=>'Margarinas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Mariscos Enlatados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Máscara de pestañas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Mayonesa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'104','name'=>'Medicamentos de Patente'));
        DB::table('subcategories')->insert(array('categorie_id'=>'97','name'=>'Medicamentos Genéricos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'37','name'=>'Mermelada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'Mezcal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'37','name'=>'Miel'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Mix de Semillas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'95','name'=>'Mole y aceitunas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'52','name'=>'Mole y Adobo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Mortadela, salchichón y pastel'));
        DB::table('subcategories')->insert(array('categorie_id'=>'110','name'=>'Multivitamínicos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'35','name'=>'Musculares e Inflamación'));
        DB::table('subcategories')->insert(array('categorie_id'=>'27','name'=>'Néctar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Nueces y Almendras'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Oaxaca y requesón'));
        DB::table('subcategories')->insert(array('categorie_id'=>'69','name'=>'Orgánicos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'30','name'=>'Oscura y Ámbar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Paletas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Palillos y popotes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Palomitas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Pan Árabe'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Pan de Caja'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Pan Dulce y Pastelitos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Pan Tostado'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Pañales - Etapa 2'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Pañales - Etapa 3'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Pañales - Etapa 4'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Pañales - Etapa 5'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Pañales - Etapa 6'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Pañales - Etapa 7'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Pañales - Recién Nacido y Etapa 1'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Panela'));
        DB::table('subcategories')->insert(array('categorie_id'=>'108','name'=>'Pañuelos desechables'));
        DB::table('subcategories')->insert(array('categorie_id'=>'80','name'=>'Papas Congeladas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Papas y Frituras'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Papel aluminio y adherente'));
        DB::table('subcategories')->insert(array('categorie_id'=>'93','name'=>'Papel higiénico'));
        DB::table('subcategories')->insert(array('categorie_id'=>'31','name'=>'Papila 1ra etapa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'31','name'=>'Papila 2da etapa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'31','name'=>'Papilla 3era etapa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'31','name'=>'Papilla 4a etapa y junior'));
        DB::table('subcategories')->insert(array('categorie_id'=>'61','name'=>'Para Hot Cakes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'82','name'=>'Para Leche'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Parmesano'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Pasta'));
        DB::table('subcategories')->insert(array('categorie_id'=>'57','name'=>'Pasta dental'));
        DB::table('subcategories')->insert(array('categorie_id'=>'57','name'=>'Pasta dental especializada'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Pasta Especial'));
        DB::table('subcategories')->insert(array('categorie_id'=>'39','name'=>'Pasta y Sopa Instantánea'));
        DB::table('subcategories')->insert(array('categorie_id'=>'99','name'=>'Pastillas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'74','name'=>'Pay y Pasteles'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Pechuga de pavo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'22','name'=>'Pepitas y Pistaches'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Pepperoni'));
        DB::table('subcategories')->insert(array('categorie_id'=>'80','name'=>'Pescados y Mariscos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'58','name'=>'Pilas y baterías'));
        DB::table('subcategories')->insert(array('categorie_id'=>'50','name'=>'Plantillas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'80','name'=>'Pollo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Polvo compacto'));
        DB::table('subcategories')->insert(array('categorie_id'=>'82','name'=>'Polvo para Agua'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Pomadas Antisépticas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Pomadas y ungüentos para bebé'));
        DB::table('subcategories')->insert(array('categorie_id'=>'34','name'=>'Postres'));
        DB::table('subcategories')->insert(array('categorie_id'=>'72','name'=>'Pozolero de maíz'));
        DB::table('subcategories')->insert(array('categorie_id'=>'101','name'=>'Predoblados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'64','name'=>'Premios y Carnazas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'79','name'=>'Primera etapa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Probióticos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'100','name'=>'Probióticos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Protector y bálsamo labial'));
        DB::table('subcategories')->insert(array('categorie_id'=>'106','name'=>'Proteínas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'97','name'=>'Pruebas de Embarazo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'39','name'=>'Puré Instantáneo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Quemaduras y protectores'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Queso de cabra'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'Queso Mozzarella'));
        DB::table('subcategories')->insert(array('categorie_id'=>'53','name'=>'queso Provolone'));
        DB::table('subcategories')->insert(array('categorie_id'=>'24','name'=>'Quitaesmaltes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'88','name'=>'Quitamanchas en Polvo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'88','name'=>'Quitamanchas Líquido'));
        DB::table('subcategories')->insert(array('categorie_id'=>'81','name'=>'Reducida en grasa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Repelentes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'61','name'=>'Repostería'));
        DB::table('subcategories')->insert(array('categorie_id'=>'91','name'=>'Rojo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'90','name'=>'Rompope'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'Ron'));
        DB::table('subcategories')->insert(array('categorie_id'=>'101','name'=>'Ropa interior'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Rubores y Bronceadores'));
        DB::table('subcategories')->insert(array('categorie_id'=>'33','name'=>'Sabor Cola'));
        DB::table('subcategories')->insert(array('categorie_id'=>'33','name'=>'Sabores Varios'));
        DB::table('subcategories')->insert(array('categorie_id'=>'61','name'=>'Saborizantes Artificiales'));
        DB::table('subcategories')->insert(array('categorie_id'=>'52','name'=>'Sal y Condimentos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Salchichas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Salchichas para asar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Salsa de Soya y Teriyaki'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Salsa para Pasta y Pizza'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Salsa Picante'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Salsas Caseras'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Salsas para Sazonar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'51','name'=>'Salsas y Complementos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'90','name'=>'Sangritas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'52','name'=>'Sazonadores'));
        DB::table('subcategories')->insert(array('categorie_id'=>'79','name'=>'Segunda etapa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'66','name'=>'Semillas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Servilletas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Shampoo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Shampoo Anticaspa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Shampoo Infantil'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Shampoo Seco'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Shampoos profesionales y tratamientos capilares'));
        DB::table('subcategories')->insert(array('categorie_id'=>'44','name'=>'Sidras'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Sin Azúcar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'69','name'=>'Sin Azúcar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'69','name'=>'Sin gluten'));
        DB::table('subcategories')->insert(array('categorie_id'=>'102','name'=>'Soluciones Antisépticas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'107','name'=>'Soluciones para Lentes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Sombra para ojos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Sopa de pasta'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Sopas y Cremas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'71','name'=>'Suavizante Especializado'));
        DB::table('subcategories')->insert(array('categorie_id'=>'71','name'=>'Suavizante Regular'));
        DB::table('subcategories')->insert(array('categorie_id'=>'100','name'=>'Sueros'));
        DB::table('subcategories')->insert(array('categorie_id'=>'97','name'=>'Suplementos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'98','name'=>'Suplementos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'106','name'=>'Suplementos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'110','name'=>'Suplementos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'78','name'=>'Sustituto de Azúcar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'80','name'=>'Tacos, pizzas y pastas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'48','name'=>'Tagliatelle'));
        DB::table('subcategories')->insert(array('categorie_id'=>'73','name'=>'Talco y aceite para bebé'));
        DB::table('subcategories')->insert(array('categorie_id'=>'50','name'=>'Talcos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Té de frutas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Té de Hierbas y Especias'));
        DB::table('subcategories')->insert(array('categorie_id'=>'83','name'=>'Té listo para beber'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Té Verde'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'Tequila'));
        DB::table('subcategories')->insert(array('categorie_id'=>'79','name'=>'Tercera y cuarta etapa'));
        DB::table('subcategories')->insert(array('categorie_id'=>'68','name'=>'Tés Medicinales'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Tinte femenino'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Tinte masculino'));
        DB::table('subcategories')->insert(array('categorie_id'=>'36','name'=>'Típicos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Toallas de cocina'));
        DB::table('subcategories')->insert(array('categorie_id'=>'101','name'=>'Toallas Húmedas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'101','name'=>'Toallas Protectoras'));
        DB::table('subcategories')->insert(array('categorie_id'=>'60','name'=>'Toallas y tampones'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Toallitas Desinfectantes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Toallitas faciales'));
        DB::table('subcategories')->insert(array('categorie_id'=>'59','name'=>'Toallitas húmedas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'38','name'=>'Tocino'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Tortillas de Harina'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Tortillas de Maíz'));
        DB::table('subcategories')->insert(array('categorie_id'=>'109','name'=>'Tos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Tostadas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'21','name'=>'Totopos y Sopes'));
        DB::table('subcategories')->insert(array('categorie_id'=>'46','name'=>'Tratamiento capilar'));
        DB::table('subcategories')->insert(array('categorie_id'=>'25','name'=>'Tratamiento corporal'));
        DB::table('subcategories')->insert(array('categorie_id'=>'23','name'=>'Tratamiento facial'));
        DB::table('subcategories')->insert(array('categorie_id'=>'75','name'=>'Tratamientos Femeninos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'92','name'=>'Vasos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'49','name'=>'Vasos y platos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'47','name'=>'Vegetales Enlatados'));
        DB::table('subcategories')->insert(array('categorie_id'=>'56','name'=>'Velas y Veladoras'));
        DB::table('subcategories')->insert(array('categorie_id'=>'94','name'=>'Verduras Congeladas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'42','name'=>'Vinagre'));
        DB::table('subcategories')->insert(array('categorie_id'=>'44','name'=>'Vino Blanco'));
        DB::table('subcategories')->insert(array('categorie_id'=>'44','name'=>'Vino Rosado'));
        DB::table('subcategories')->insert(array('categorie_id'=>'44','name'=>'Vino Tinto'));
        DB::table('subcategories')->insert(array('categorie_id'=>'110','name'=>'Vitaminas'));
        DB::table('subcategories')->insert(array('categorie_id'=>'105','name'=>'Vitaminas y Suplementos'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'Vodka'));
        DB::table('subcategories')->insert(array('categorie_id'=>'26','name'=>'Whisky'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Yogur Batido'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Yogur Bebible'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Yogur deslactosado y vegano'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Yogur Digestivo'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Yogur Griego'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Yogur Light'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Yogur Natural'));
        DB::table('subcategories')->insert(array('categorie_id'=>'43','name'=>'Yogur para niños'));
        DB::table('subcategories')->update(['code'=>'name']);




    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('subcategories');
    }
};
